baseURL: "http://blog.darrelpol.com/"
title: Darrel Pol
paginate: 5
theme: PaperMod

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

googleAnalytics: G-64HBEKP88J

minify:
  disableXML: true
  minifyOutput: true

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: darrelpol.com
  description: "Hi there \U0001F44B! Welcome to my blog, where I talk Tech, Productivity, and Habit Creations."
  keywords: [Blog, Portfolio, PaperMod]
  author: Darrel Pol
  # author: ["Me", "You"] # multiple authors
  images: ["<link or path of image for opengraph, twitter-cards>"]
  DateFormat: "January 2, 2006"
  defaultTheme: auto # dark, light
  disableThemeToggle: false

  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowWordCount: true
  ShowRssButtonInSectionTermList: false
  UseHugoToc: true
  disableSpecial1stPost: false
  disableScrollToTop: true
  comments: true
  hidemeta: false
  hideSummary: false
  showtoc: false
  tocopen: false

  assets:
    # disableHLJS: true # to disable highlight.js
    # disableFingerprinting: true
    favicon: "<link / abs url>"
    favicon16x16: "<link / abs url>"
    favicon32x32: "<link / abs url>"
    apple_touch_icon: "<link / abs url>"
    safari_pinned_tab: "<link / abs url>"

  label:
    text: "Home"
    icon: /apple-touch-icon.png
    iconHeight: 35

  # profile-mode
  profileMode:
    enabled: true # needs to be explicitly set
    title: Darrel Pol
    subtitle: "Hi there \U0001F44B! Welcome to my blog, where I talk Tech, Productivity, and Habit Creations."
    imageUrl: "/profile_picture.jpeg"
    imageWidth: 300
    imageHeight: 300
    imageTitle: darrel pol profile picture
    buttons:
      - name: Posts
        url: posts
      # - name: Tags
      #   url: tags

  # home-info mode
  homeInfoParams:
    Title: "Hi there \U0001F44B"
    Content: Hi there \U0001F44B! Welcome to my blog, where I talk Tech, Productivity, and Habit Creations.

  socialIcons:
    - name: email
      url: "mailto:poldarrel@gmail.com"
    - name: linkedin
      url: "https://www.linkedin.com/in/darrelpol/"      
    - name: twitter
      url: "https://twitter.com/darrelpoldev"
    - name: github
      url: "https://github.com/poldarreldev"


  # analytics:
  #   google:
  #     SiteVerificationTag: "XYZabc"
  #   bing:
  #     SiteVerificationTag: "XYZabc"
  #   yandex:
  #     SiteVerificationTag: "XYZabc"

  cover:
    hidden: true # hide everywhere but not in structured data
    hiddenInList: true # hide on list pages and home
    hiddenInSingle: true # hide on single page

  editPost:
    URL: "https://github.com/blog.darrelpol.com/tree/main/content"
    Text: "Suggest Changes" # edit text
    appendFilePath: true # to append file path to Edit link

  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]
menu:
  main:
    # - identifier: categories
    #   name: categories
    #   url: /categories/
    #   weight: 10
    # - identifier: tags
    #   name: tags
    #   url: /tags/
    #   weight: 20
    - identifier: DarrelPol
      name: darrelpol.com
      url: http://blog.darrelpol.com
      weight: 30
# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
pygmentsUseClasses: true
markup:
  highlight:
    noClasses: false
    # anchorLineNos: true
    # codeFences: true
    # guessSyntax: true
    # lineNos: true
    # style: monokai