baseURL: "https://darrelpol.com/"
title: Darrel Pol
paginate: 10
theme: PaperMod

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

googleAnalytics: G-30W23X1RW8

minify:
  disableXML: true
  minifyOutput: true

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: darrelpol.com
  description: "Hi there \U0001F44B! Welcome to my blog, where I talk Tech, Productivity, and Habit Creations."
  keywords: [Blog, Portfolio, PaperMod]
  author: Darrel Pol
  # author: ["Me", "You"] # multiple authors
  images: ["<link or path of image for opengraph, twitter-cards>"]
  DateFormat: "January 2, 2006"
  defaultTheme: auto # dark, light
  disableThemeToggle: false
  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowWordCount: true
  ShowRssButtonInSectionTermList: false
  UseHugoToc: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: true
  hidemeta: false
  hideSummary: false
  showtoc: false
  tocopen: true
  ShareButtons: ["linkedin", "twitter"]
  assets:
    # disableHLJS: true # to disable highlight.js
    # disableFingerprinting: true
    favicon: "/favicon.ico"
    favicon16x16: "/favicon-16x16.png"
    favicon32x32: "/favicon-32x32.png"
    apple_touch_icon: "/apple-touch-icon.png"
    safari_pinned_tab: "/favicon.ico"

  label:
    text: "Home"
    icon: /apple-touch-icon.png
    iconHeight: 35

  # profile-mode
  profileMode:
    enabled: true # needs to be explicitly set
    title: Darrel Pol
    subtitle: "Hi there \U0001F44B! Welcome to my blog, where I talk Tech, Productivity, and Habit Creations."
    imageUrl: "/profile_picture.jpeg"
    imageWidth: 300
    imageHeight: 300
    imageTitle: darrel pol profile picture
    buttons:
      - name: Posts
        url: posts
      - name: Tags
        url: tags

  # home-info mode
  homeInfoParams:
    Title: "Hi there \U0001F44B"
    Content: Hi there \U0001F44B! Welcome to my blog, where I talk Tech, Productivity, and Habit Creations.

  socialIcons:
    - name: email
      url: "mailto:poldarrel.dev@gmail.com"
    - name: linkedin
      url: "https://www.linkedin.com/in/darrelpol/"
    - name: github
      url: "https://github.com/darrelpoldev"
    - name: twitter
      url: "https://twitter.com/darrelpoldev"
    - name: kofi
      url: "https://ko-fi.com/darrelpol"  


  # analytics:
  #   google:
  #     SiteVerificationTag: "XYZabc"
  #   bing:
  #     SiteVerificationTag: "XYZabc"
  #   yandex:
  #     SiteVerificationTag: "XYZabc"

  cover:
    hidden: true # hide everywhere but not in structured data
    hiddenInList: true # hide on list pages and home
    hiddenInSingle: true # hide on single page

  editPost:
    URL: "https://github.com/darrelpol.com/tree/main/content"
    Text: "Suggest Changes" # edit text
    appendFilePath: true # to append file path to Edit link

  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]
menu:
  main:
    # - identifier: categories
    #   name: categories
    #   url: /categories/
    #   weight: 10
    - identifier: ko-fi
      name: Buy me a Coffee!
      url: https://ko-fi.com/darrelpol
      weight: 20
# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
pygmentsUseClasses: true
markup:
  highlight:
    noClasses: false
    anchorLineNos: true
    # codeFences: true
    # guessSyntax: true
    lineNos: true
    # style: monokai